# weather api
API = "https://api.seniverse.com/v3/weather/daily.json"
LANGUAGE = "zh-Hans"
KEY = "ygnfdic5sis9nfpt"
UNIT = "c"
POSTGRES_USER = "postgres"
POSTGRES_PW = "swan"
POSTGRES_URL = "127.0.0.1:5432"
POSTGRES_DB = "weather128"